name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:12.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
